[tool.poetry]
name = "untitled" # ! ðŸ‘ˆ Change this to your project name
version = "0.0.1" # ! ðŸ‘ˆ Change this to your project version
description = "No description" # ! ðŸ‘ˆ Change this to your project description
license = "MIT" # ! ðŸ‘ˆ Change this to your project license
authors = [
    "Your Name <you@example.com>",
] # ! ðŸ‘ˆ Change this to your name and email
maintainers = [
    "Your Name <you@example.com>", # ! ðŸ‘ˆ Change this to your name and email
]
readme = "README.md"

packages = [
    { include = "*", from = "src" }, # ! ðŸ‘ˆ Change this to your package name
]

# ðŸ‘‡Uncomment to add HomePage
# homepage = "your-project-url" # * ðŸ‘ˆ Change this to your project URL

# ðŸ‘‡Uncomment to add Repository
# repository = "your-repository-url" # * ðŸ‘ˆ Change this to your repository URL

# ðŸ‘‡Uncomment to add Documentation
# documentation = "your-documentation-url" # * ðŸ‘ˆ Change this to your documentation URL

# ðŸ‘‡Uncomment to add classifiers
# classifiers = [
#     "Topic :: Software Development :: Libraries :: Python Modules",
#     "Programming Language :: Python :: 3",
# ]

# ðŸ‘‡Uncomment to exclude packages
# exclude = ["untitled"]


[tool.poetry.dependencies]
python = "^3.11" # ! ðŸ‘ˆ Change this to your Python version


[tool.poetry.group.dev.dependencies]
black = "^23.12.1"
ruff = "^0.1.13"
mypy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
